Add documentation for gluster-ansible-cluster role
gluster/gluster-ansible-cluster pull request #6
Opened 2018-05-21 14:15 UTC by devyanikota

Signed-off-by: Devyani Kota <devyanikota@gmail.com>

2018-05-22 03:17 UTC, sac requested changes

2018-05-22 03:17 UTC, sac commented on README.md
> +  2. gluster_volume_set - set specific options for gluster volumes
@devyanikota can't this be part of volume? That is if gluster_volume has state started/stopped and the options variables are set then the volume would set those options and leave the volume in the said state.

A separate gluster_volume_set  role would be extra work.

2018-05-22 03:17 UTC, sac commented on README.md
> +  3. gluster_brick - perform add/remove/replace operations on existing bricks
Same for this.

2018-05-22 09:37 UTC, devyanikota commented on README.md
> +  3. gluster_brick - perform add/remove/replace operations on existing bricks
sure, will rectify this.

2018-05-23 04:24 UTC, sac approved these changes
LGTM

2018-05-23 04:25 UTC, merged